language: python
python:
  - "3.5"

before_install:
  - pip install --no-index --trusted-host travis-wheels.scikit-image.org --find-links=https://travis-wheels.scikit-image.org numpy scipy
  - sudo apt-get install ffmpeg

#command to install dependencies
install:
  - pip install librosa

#command to run tests
script: nosetests

sudo: required
