language: python
python:
  - "3.5"

before_install:
  - pip install numpy scipy coverage
  - sudo apt-get install ffmpeg

#command to install dependencies
install:
  - pip install librosa

#command to run tests
script: nosetests --exe --with-coverage

sudo: required
